set(LDFLAGS "-lz -L${INSTALL_ROOT}/hdf5/lib -lhdf5 -no-pie" CACHE STRING "LDFLAGS" FORCE)

set(CMAKE_HOST_FLAGS "")

ExternalProject_Add(
    Octotiger
    
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/octotiger
    GIT_REPOSITORY https://github.com/STEllAR-GROUP/octotiger.git
    GIT_PROGRESS FALSE
    # CMAKE_COMMAND ${CMAKE_CURRENT_BINARY_DIR}/build/cmake/bin/cmake
    INSTALL_DIR ${CMAKE_CURRENT_BINARY_DIR}/octotiger/build
    CMAKE_ARGS 
        -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR> 
        -DCMAKE_PREFIX_PATH=<PEFIX> 
        -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
        -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
        -DCMAKE_CUDA_HOST_COMPILER=${CMAKE_CUDA_HOST_COMPILER}
        -DCMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD}
        -DCMAKE_CUDA_STANDARD=${CMAKE_CUDA_STANDARD}
        -DHPX_DIR=${CMAKE_CURRENT_BINARY_DIR}/build/hpx/lib/cmake/HPX/ 
        -DSilo_DIR=${CMAKE_CURRENT_BINARY_DIR}/build/silo 
        -DCMAKE_CXX_FLAGS=-fpermissive -std=c++17 
        -DVc_DIR=${INSTALL_ROOT}/Vc/lib/cmake/Vc 
        -DOCTOTIGER_WITH_BLAST_TEST=OFF 
        -DHDF5_ROOT=${INSTALL_ROOT}/hdf5/
        -DBoost_NO_SYSTEM_PATHS=ON
        -DBOOST_ROOT=${BOOST_ROOT}
        -DCMAKE_EXE_LINKER_FLAGS=${LDCXXFLAGS}\ -lz\ -L${INSTALL_ROOT}/hdf5/lib\ -lhdf5 
        -DOCTOTIGER_WITH_CUDA=${OCT_WITH_CUDA}
        -DCUDA_NVCC_FLAGS=-Xcompiler=-fPIC
        -DCMAKE_BUILD_TYPE=Release
    BUILD_IN_SOURCE FALSE
    # BUILD_ALWAYS ON
    DEPENDS ${OCTOTIGER_DEPENDENCIES}
)
